version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fullstack_backend
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/expense_db
      - JWT_SECRET_KEY=mysecret
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: fullstack_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: expense_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data: